#!/bin/bash

cd ~/Desktop/mlops-heart-disease-project

echo "╔════════════════════════════════════════════════════════════╗"
echo "║        MLOps Heart Disease Project - READY TO RUN         ║"
echo "║            Umang Sharma (2024AC05070)                      ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Virtual environment: READY"
echo "✅ Dependencies: INSTALLED"
echo "✅ Dataset: DOWNLOADED (UCI Heart Disease)"
echo "   - Source: UCI Machine Learning Repository"
echo "   - 303 patients, 14 features"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "WHAT TO RUN:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option 1: Start Jupyter Notebooks (RECOMMENDED)"
echo "  ./venv/bin/jupyter notebook"
echo ""
echo "  Then open:"
echo "  - notebooks/01_eda_preprocessing.ipynb"
echo "  - notebooks/02_model_training.ipynb"
echo ""
echo "Option 2: Run scripts directly"
echo "  ./venv/bin/python src/data/preprocess.py"
echo "  ./venv/bin/python src/models/train.py"
echo ""
echo "Option 3: Start API server"
echo "  ./venv/bin/uvicorn src.api.app:app --reload"
echo ""
echo "Option 4: View MLflow experiments"
echo "  ./venv/bin/mlflow ui"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "QUICK START:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Just run:"
echo "  ./venv/bin/jupyter notebook"
echo ""
echo "Browser will open automatically!"
echo "📸 Remember to take screenshots of everything!"
echo ""
