apiVersion: v1
kind: Service
metadata:
  name: heart-disease-predictor-service
  labels:
    app: heart-disease-predictor
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: heart-disease-predictor
